dataset:
  target: dataset.lic_full_erp.LICFullERPDataset
  params:
    file_list: ./datalists/valid.list
    long_edge: 1024
    multiple: 64
    vertical_pad_mode: reflect
    vertical_pad_value: 0.0
    random_roll: false

data_loader:
  batch_size: 1
  shuffle: false
  num_workers: 4
  drop_last: false

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
