# configs/dataset/lic_train_full.yaml
dataset:
  target: dataset.lic_full_erp.LICFullERPDataset
  params:
    file_list: datalists/train.list
    long_edge: 1536        # 示例
    multiple: 64
    vertical_pad_mode: constant  # 跟 SMGD 对齐；也可用 reflect
    vertical_pad_value: 0.0
    random_roll: true
    random_roll_max: 128   # 可省略，默认 W-1
    extra_hwrap_px: 4      # 训练更激进一点（2~4）


data_loader:
  batch_size: 2          # 依据显存调整
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
