# configs/dataset/lic_train_full.yaml
dataset:
  target: dataset.lic_full_erp.LICFullERPDataset
  params:
    file_list: ./datalists/train.list
    # 按显存调：例如 1024 -> (H,W) 约等比到长边 1024 再 pad
    long_edge: 1024
    # UNet/SD 下采样链约束（VAE×8 * UNet×8），建议 64
    multiple: 64
    # 纵向 pad 策略（极区更稳），与我们卷积前置处理一致
    vertical_pad_mode: reflect   # reflect | replicate | constant
    vertical_pad_value: 0.0
    # 训练集可开，验证/推理务必关
    random_roll: true

data_loader:
  batch_size: 2          # 依据显存调整
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
